name: Example workflow using Snyk
on: push
jobs:
  snyk_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Snyk CLI
      run: |
        curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
        chmod +x snyk
        sudo mv snyk /usr/local/bin/

    - name: Authenticate Snyk CLI
      run: |
        snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Run Snyk to test project dependencies
      run: |
        snyk test